<?php
/*
Template Name: Register
*/

get_header(); ?>

<main>
    <section class="container mt-52">
        <div id="app">
            This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in
            WordPress.
        </div><!-- #vue-app -->
    </section>
</main>

<?php get_footer(); ?>